# Generated by Django 5.1.7 on 2025-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20250325_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='region',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
