# Generated by Django 5.1.7 on 2025-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_campus_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={},
        ),
        migrations.AlterModelManagers(
            name='responsable',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='password',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='username',
        ),
        migrations.AddField(
            model_name='responsable',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
